const mockData = [
    {
      subject_name: null,
      report_date: null,
      report_uid: null,
      requested_by: null,
      purpose: null,
      report_no: null,
      subject_type: null,
      report_type: null,
      status: null,
    },
    {
      subject_name: null,
      report_date: null,
      report_uid: null,
      requested_by: null,
      purpose: null,
      report_no: null,
      subject_type: null,
      report_type: null,
      status: null,
    },
    {
      subject_name: null,
      report_date: null,
      report_uid: null,
      requested_by: null,
      purpose: null,
      report_no: null,
      subject_type: null,
      report_type: null,
      status: null,
    },
    {
      subject_name: null,
      report_date: null,
      report_uid: null,
      requested_by: null,
      purpose: null,
      report_no: null,
      subject_type: null,
      report_type: null,
      status: null,
    },
];

const relationshipObj = {
  "D":"Director",
  "S":"Shareholder",
  "DS":"Director/Shareholder",
  "P":"Partner",
  "SP":"Sole Proprieter",
  "AD":"Alternate Director",
  "AS":"Alternate Director/Shareholder",
  "G":"Guarantor",
  "JO":"Joint Owner",
  "O":"Others",
}

export { mockData, relationshipObj };