module.exports = [
  {
    image: require("../../assets/image/buy-report.png"),
    text1: "general_buy_report",
    text2: "Report",
    navigate: "",
    modalName: "Buy Report",
    modalId: "buy_report",
    isModal: true,
  },
  {
    image: require("../../assets/image/view-report.png"),
    text1: "general_view_report",
    text2: "Report",
    navigate: "Reports",
    activeOption: 1,
    modalId: "",
    isModal: false,
  },
  {
    image: require("../../assets/image/add-monitor.png"),
    text1: "general_add_monitor",
    text2: "Monitoring",
    navigate: "AddMonitoring",
    modalName: "Add Monitoring",
    modalId: "add_monitoring",
    isModal: true,
  },
  {
    image: require("../../assets/image/view-monitor.png"),
    text1: "general_view_monitor",
    text2: "Monitoring",
    navigate: "Monitor",
    activeOption: 2,
    modalId: "",
    isModal: false,
  },
  {
    image: require("../../assets/image/view-etr-submitted.png"),
    text1: "general_view_etr_submitted",
    text2: "Submitted",
    navigate: "etrSubmit",
    activeOption: 3,
    subActive: 4,
    modalId: "",
    isModal: false,
  },
  {
    image: require("../../assets/image/view-etr-reached.png"),
    text1: "general_view_etr_reached",
    text2: "Reached",
    navigate: "etrReach",
    activeOption: 3,
    subActive: 5,
    modalId: "",
    isModal: false,
  },
];
